title: "Jinesh Gada"
description: "Technical Lead · Automotive Software Engineer · Diagnostics & OTA Expert"
theme: jekyll-theme-cayman
show_downloads: false

author:
  name: "Jinesh Gada"
  email: "301jinesh.gada@gmail.com"
  linkedin: "https://linkedin.com/in/jinesh-gada-2975aa106"
